//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Shirel_Ferrera.DAL
{
    using System;
    using System.Collections.Generic;
    
    public partial class Airlines
    {
        public string Code { get; set; }
        public string AirlineName { get; set; }
        public int ID { get; set; }
    }
}
